apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: renukashweta/back-image:latest
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017/reactdb
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
