apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
<<<<<<< HEAD
        image: 809581002932.dkr.ecr.ap-south-1.amazonaws.com/react-mongo:latest
=======
        image: 809581002932.dkr.ecr.ap-south-1.amazonaws.com/react-mongo
>>>>>>> cc25490 (Reconnect project after accidental .git deletion)
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: react-app
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
