name: CI/CD with Docker and ArgoCD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'k8s/**'
      - '.github/workflows/**'

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.IMAGE_NAME_BACKEND }}:${{ env.IMAGE_TAG }} ./backend
        docker push ${{ secrets.IMAGE_NAME_BACKEND }}:${{ env.IMAGE_TAG }}

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.IMAGE_NAME_FRONTEND }}:${{ env.IMAGE_TAG }} ./frontend
        docker push ${{ secrets.IMAGE_NAME_FRONTEND }}:${{ env.IMAGE_TAG }}

    - name: Update Kubernetes manifests
      run: |
        sed -i "s|image: .*back-image.*|image: ${{ secrets.IMAGE_NAME_BACKEND }}:${{ env.IMAGE_TAG }}|" ./k8s/backend-deployment.yaml
        sed -i "s|image: .*front-image.*|image: ${{ secrets.IMAGE_NAME_FRONTEND }}:${{ env.IMAGE_TAG }}|" ./k8s/frontend-deployment.yaml

    - name: Configure git
      run: |
        git config user.name "${{ secrets.GIT_USERNAME }}"
        git config user.email "${{ secrets.GIT_EMAIL }}"

    - name: Commit updated manifests
      run: |
        git add k8s/
        git commit -m "Update image tags to ${{ env.IMAGE_TAG }}"
        git push origin main
