name: CI/CD with Docker + ArgoCD

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Backend Image
      run: |
        docker build -t renukashweta/back-image:${{ env.IMAGE_TAG }} ./backend
        docker push renukashweta/back-image:${{ env.IMAGE_TAG }}

    - name: Build & Push Frontend Image
      run: |
        docker build -t renukashweta/front-image:${{ env.IMAGE_TAG }} ./frontend
        docker push renukashweta/front-image:${{ env.IMAGE_TAG }}

    - name: Update K8s Manifests with New Tags
      run: |
        sed -i "s|image: renukashweta/back-image:.*|image: renukashweta/back-image:${{ env.IMAGE_TAG }}|" k8s/backend-deployment.yaml
        sed -i "s|image: renukashweta/front-image:.*|image: renukashweta/front-image:${{ env.IMAGE_TAG }}|" k8s/frontend-deployment.yaml

       
    - name: Commit & Push Updated Manifests
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}
        git add k8s/
        git commit -m "Update image tags to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
        git push origin main

